### ISSUE TITLE
Problem with start

### ISSUE THREAD

**Issue by sanket044** [jamiebicknell/Sparkline#3]
Hello,

Thank you for your great work. I have some problem with making graphs. If I have two points it 0 and 1 it should show in two corners but it is starting from the middle.

**Comment by jamiebicknell** [comment]
Hello,

I've created a sparkline with 2 points (0,1) and I've attached the output, which is the correct output for these two points.

![sparkline_1511769710044](https://user-images.githubusercontent.com/326427/33256330-86fae894-d349-11e7-9e8d-6a2a430dec37.png)

Therefore cannot recreate your issue. If you could provide more information like the query string parameters to generate your sparkline then I might be able to troubleshoot further.

**Comment by sanket044** [comment]
Hello,

Sorry my mistake, (0,1) works perfectly. But same is not working with 100,101. It should also show same graph as (0,1) right? But it shows flat line.

http://localhost/sparkline.php?data=100,101&size=166x50 <http://localhost/sparkline.php?data=100,101&size=166x50>

Warm Regards,
Sanket Mehta.
programmer044@gmail.com

**Comment by jamiebicknell** [comment]
Hello Sanket,

That's a very interesting point actually. I'll have a play around tonight and see what's best to do.

I think you're right in that it needs to normalise the figures, so the lowest figure is 0.

**Comment by sanket044** [comment]
Great. Thank you for your reply.

**Comment by sanket044** [comment]
I just got an idea from your last comment and added following code after line number 23 and it worked also.

```
$minData = min($data);
foreach($data as $key=>$val) {
	$data[$key] = $val-$minData;
}
```

**Comment by jamiebicknell** [comment]
That would work as a quick fix, however a side affect of this is that for an array of values like `10,10,10,10,10` it would change this to `0,0,0,0,0` and the question would be whether the chart should display a line at the bottom (implying no data) or at the top with the fill (implying data is present).

How Google Charts handle this is that instead of having the line at the bottom or the top they have it vertically in the middle, which I'm not a fan of.

A potential solution could be to only adjust the values if the min and the max aren't the same, that way `100,101` is converted to `0,1` and `100,100` remains `100,100`.

This can be done via:

```php
$min = min($data);
$max = max($data);
if ($max != $min) {
    foreach ($data as $k => $v) {
        $data[$k] -= $min;
    }
}
```

**Comment by sanket044** [comment]
That would be a perfect solution.

**Comment by GuilVII** [comment]
Hi, first of all thanks a lot for your great work. I'm facing similar issue as above about the minimum low value. Let's say I have the following values: 8000,9000,8500,11000,10500,10200
Google charts would show the following graph:

![capture d ecran 2017-12-02 a 12 26 17](https://user-images.githubusercontent.com/34185715/33514956-34933680-d75c-11e7-8f2f-f8c3b2c855ff.png)

However your minimum value being 0 by default, your sparkline graph will show:

![capture d ecran 2017-12-02 a 12 29 48](https://user-images.githubusercontent.com/34185715/33514976-98954128-d75c-11e7-99a9-5eb87a3d1a6e.png)

Any idea how could I easily tweak this? The above solution is not working.

Thanks a lot

**Comment by sanket044** [comment]
Hello, please find above answer by jamiebicknell, add new code in sparkline.php file and the problem will be solved.
